[package]
name = "nyxc_lexer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
phf = { version = "0.11.1", features = ["macros"] }
unicode-ident = "1.0.5"
rustyline = "10.0.0"
