[package]
name = "nyxc_typechecker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nyxc_ast = { path = "../nyxc_ast/" }
nyxc_parser = { path = "../nyxc_parser/" }
rustyline = "10.0.0"
